"""
Location: tests/test_published_surfaces.py
Purpose: Catch the failure this file was written for: the repo's PUBLISHED surfaces (README,
         RESULTS.md, RESULTS_T01.md, the paired report) drifting away from the data they claim to
         describe. Before v1.3.0, results/RESULTS.md still said "11 models" after a 12th had been
         measured and committed -- nothing in the suite could tell, because every existing test
         checked the GENERATOR and none checked the generated ARTIFACT on disk.
         The load-bearing check is idempotency: regenerating every surface must change nothing.
         If it changes something, what is committed is stale, and the release would ship it.
Functions: TestGeneratedSurfacesAreCurrent, TestNoStaleModelCounts, TestReadmeClaimsMatchData
Imports: hashlib, json, subprocess, sys, pytest, pathlib
"""

import hashlib
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "results"))
sys.path.insert(0, str(ROOT / "engine"))

import aggregate as ag  # noqa: E402

SURFACES = ["README.md", "results/RESULTS.md", "results/RESULTS_T01.md",
            "results/PAIRED_legacy_vs_t01.md"]


def _digest():
    h = hashlib.sha256()
    for name in SURFACES:
        h.update((ROOT / name).read_bytes())
    return h.hexdigest()


class TestGeneratedSurfacesAreCurrent:
    def test_regenerating_every_surface_changes_nothing(self):
        """The whole point. `make render` regenerates all four from disk; if the committed bytes
        differ from the regenerated bytes, a published number no longer matches the data.

        Runs the real generators rather than reimplementing them -- a check that recomputed the
        numbers itself would only prove it agrees with itself.
        """
        original = {n: (ROOT / n).read_bytes() for n in SURFACES}
        before = _digest()
        try:
            for cmd in (["results/render.py"], ["results/render.py", "--temperature", "0.1"],
                        ["results/compare.py"], ["results/temp_readme.py"]):
                r = subprocess.run([sys.executable] + [str(ROOT / cmd[0])] + cmd[1:],
                                   cwd=ROOT, capture_output=True, text=True)
                assert r.returncode == 0, f"{cmd} failed: {r.stderr[-400:]}"
            after = _digest()
        finally:
            # RESTORE. Regenerating is how this test works, but leaving the regenerated bytes
            # behind makes the suite mutate the developer's tree AND repairs staleness that other
            # tests exist to detect: with a stale count planted, this test ran first, silently
            # rewrote the file, and the stale-count test below then passed on the repaired copy.
            # A test whose side effect hides another test's failure is worse than no test.
            for n, data in original.items():
                (ROOT / n).write_bytes(data)
        assert after == before, (
            "a published surface is STALE: regenerating it produced different bytes. "
            "Run `make render` and commit the result.")


class TestNoStaleModelCounts:
    """A model count written in prose is a claim about the data, and it rots silently."""

    @pytest.mark.parametrize("name", SURFACES)
    def test_no_surface_states_a_wrong_model_count(self, name):
        text = (ROOT / name).read_text()
        n = len(ag.canonical_lineup())
        for m in re.finditer(r"\b(\d+) models\b", text):
            assert int(m.group(1)) == n, (
                f"{name} says '{m.group(0)}' but the lineup has {n}. This is exactly how "
                f"results/RESULTS.md came to claim 11 models after a 12th was measured.")

    def test_the_check_can_actually_fire(self):
        """Positive control: the pattern must match real prose, or the test above is vacuous."""
        assert re.search(r"\b(\d+) models\b", "12 models span a size ladder")
        assert not re.search(r"\b(\d+) models\b", "no count here")


class TestReadmeClaimsMatchData:
    def test_built_leaf_count_is_correct(self):
        text = (ROOT / "README.md").read_text()
        n = len(ag.built_leaves())
        assert f"{n} tests" in text or f"{n} leaves" in text, \
            f"README does not state the real built-leaf count ({n})"

    def test_registry_split_is_stated_not_just_the_total(self):
        """The README used to say '67 atomic checks' without saying 60 were built -- true, but it
        reads as 67 measured. A backlog total and a measured total are different claims."""
        text = (ROOT / "README.md").read_text()
        assert "67 atomic checks" in text
        assert f"**{len(ag.built_leaves())} are built and measured**" in text

    def test_readme_does_not_claim_a_single_temperature(self):
        """Both arms are published now. A README that says the benchmark runs 'at temperature 0.7'
        describes a benchmark that no longer exists."""
        text = (ROOT / "README.md").read_text()
        prose = text.split("<!-- BENCHMARK:START -->")[0]
        assert "20 times at temperature 0.7" not in prose
        assert "two temperatures" in prose

    def test_the_temperature_block_is_present_and_generated(self):
        text = (ROOT / "README.md").read_text()
        assert "<!-- TEMPCOMPARE:START -->" in text and "<!-- TEMPCOMPARE:END -->" in text
        block = text.split("<!-- TEMPCOMPARE:START -->")[1].split("<!-- TEMPCOMPARE:END -->")[0]
        assert "wobbled less at" in block, "the temperature block is empty -- run make render"
